In [2]:
import pandas as pd

In [50]:
df = pd.read_csv('../data/raw/listings.csv', encoding='utf-8')
df.shape
df.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20260614073253,2026-06-15,city scrape,11 Min to Manhattan • Prospect Park • Fast WiFi,"Bright, serene room in a renovated apartment h...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.78,4.78,NaN,NaN,5,0,5,0,0.08
1,6848,https://www.airbnb.com/rooms/6848,20260614073253,2026-06-14,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.95
2,6872,https://www.airbnb.com/rooms/6872,20260614073253,2026-06-14,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
3,6990,https://www.airbnb.com/rooms/6990,20260614073253,2026-06-14,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.24
4,7097,https://www.airbnb.com/rooms/7097,20260614073253,2026-06-14,city scrape,"Perfect for Your Parents, With Garden & Patio",Parents/grandparents coming to town or are you...,NaN,https://a0.muscache.com/pictures/aaac19fc-4b4d...,17571,...,4.93,4.95,4.82,NaN,NaN,2,0,2,0,2.12

In [5]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

## Requirements for data cleaning
`host_identity_verified` should be t

In [ ]:

df.groupby('').size()

Series([], dtype: int64)

In [ ]:
df[['id', 'name', 'host_id', 'host_name', 'host_is_superhost', 'host_listings_count', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 
    'room_type', 'accommodates', 'host_listings_count', 'price', 'minimum_nights', 'maximum_nights', 
    'calendar_updated', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_l30d', 'review_scores_rating']].head(10)

,id,name,host_id,host_name,host_is_superhost,host_listings_count,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,accommodates,host_listings_count,price,minimum_nights,maximum_nights,calendar_updated,calendar_last_scraped,number_of_reviews,number_of_reviews_l30d,review_scores_rating
0,2539,11 Min to Manhattan • Prospect Park • Fast WiFi,2787,John,f,5.0,Kensington,Brooklyn,Private room in condo,Private room,2,5.0,$113.97,30.0,730.0,NaN,2026-06-15,10,1,4.80
1,6848,Only 2 stops to Manhattan studio,15991,Allen,t,1.0,Williamsburg,Brooklyn,Entire rental unit,Entire home/apt,3,1.0,$117.27,30.0,240.0,NaN,2026-06-14,198,0,4.60
2,6872,Uptown Sanctuary w/ Private Bath (Month to Month),16104,Kae,f,2.0,East Harlem,Manhattan,Private room in condo,Private room,1,2.0,$80.06,30.0,180.0,NaN,2026-06-14,2,0,5.00
3,6990,UES Beautiful Blue Room,16800,Cynthia,t,1.0,East Harlem,Manhattan,Private room in rental unit,Private room,1,1.0,$77.17,30.0,120.0,NaN,2026-06-14,251,0,4.88
4,7097,"Perfect for Your Parents, With Garden & Patio",17571,Jane,t,2.0,Fort Greene,Brooklyn,Private room in guest suite,Private room,2,2.0,$202.47,30.0,1125.0,NaN,2026-06-14,423,0,4.89
5,7801,Sunny Williamsburg Loft with Private Cedar Sauna,21207,Chaya,t,3.0,Williamsburg,Brooklyn,Entire place,Entire home/apt,2,3.0,$365.97,30.0,120.0,NaN,2026-06-14,13,0,4.92
6,263005,2 bedroom apartment in charming brick townhouse,1380060,Marisa And Colin,f,1.0,Fort Greene,Brooklyn,Entire rental unit,Entire home/apt,4,1.0,$154.87,30.0,1125.0,NaN,2026-06-14,129,0,4.67
7,263232,Cozy&Clean in a great neighborhood,1381171,Nicole,f,1.0,Harlem,Manhattan,Entire rental unit,Entire home/apt,4,1.0,$91.07,30.0,30.0,NaN,2026-06-14,0,0,NaN
8,263888,Contemporary & Classic Sanctuary on the Hudson,1384559,Catherine,f,2.0,Upper West Side,Manhattan,Entire condo,Entire home/apt,2,2.0,NaN,30.0,45.0,NaN,2026-06-22,251,0,4.99
9,265145,Studio sublet in Hell's kitchen,1390947,Akiko,f,1.0,Theater District,Manhattan,Entire rental unit,Entire home/apt,2,1.0,NaN,30.0,30.0,NaN,2026-06-22,8,0,4.88